# 1. What does Pandas stand for?
## - Pandas either stands for "Panel Data" or Python Data Analysis
# 2. What are the 2 collections used in Pandas?
## 1. Arrays
## 2. Dataframes
# 3. Name 4 things Pandas can do for us.
## 1. Data Cleaning
## 2. Data Filling
## 3. Merging and Joing data sets
## 4.  Data inspection
# 4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
## - We should use the 'inplace= True' keyword combination with the df.sort() method
# 5. What is a CSV?
## - CSV stands for "Comma Separate Variables"
# 6. When cleaning data what values do we not like in our data?
## - We do not like 'Null' values, or empty cells in our data.

In [88]:
#Problem 7: Import NumPy and create an array
import numpy as np

#alist1 = [[[1,2],[3,4],[5,6]],[[7,8],[9,8],[6,5]]]
array1 = np.array([1,2,3,4,5,6,7,8,9,8,6,5])
array2 = array1.reshape(2,3,2)
print(array1)

[1 2 3 4 5 6 7 8 9 8 6 5]


In [89]:
#Problem 8: Use the '.linespace' to create an array

new_array1 = np.linspace(0,20,6)
new_list = []
for number in new_array1:
    new_list.append(int(number))
new_array = np.array(new_list)
print(new_array)

[ 0  4  8 12 16 20]


In [90]:
#Problem 9: Make a deep copy from Problem 8
import copy as cp
copy_new_array = cp.deepcopy(new_array)
print(copy_new_array)

[ 0  4  8 12 16 20]


In [109]:
#Problem 10: Concatenate the 3 arrays from Problems from 7, 8,9
import numpy as np
thisArray = ([[25, 16]])
thatArray = ([[11, 2], [13, 4]])
anyArray = ([[7, 81], [5, 6], [11, 12]])
newArray = np.concatenate((thisArray, thatArray,anyArray),axis = 0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [110]:
#Problem 11: Sorting the array from Problem 9

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [116]:
#Problem 12: Create new array from unpacking the one from the previous question
reshapedArray = sortedArray.reshape(4,3)
print(reshapedArray)
vars_a, vars_b, vars_c, vars_d = reshapedArray
print(f"variables in array a: {vars_a}")
print(f"variables in array b: {vars_b}")
print(f"variables in array c: {vars_c}")
print(f"variables in array d: {vars_d}")


[[16 25  2]
 [11  4 13]
 [ 7 81  5]
 [ 6 11 12]]
variables in array a: [16 25  2]
variables in array b: [11  4 13]
variables in array c: [ 7 81  5]
variables in array d: [ 6 11 12]


In [121]:
#Problem 13: combine 3 arrays into 1
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one,two,three), axis = 0)
print(comboArray)

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]


In [146]:
#Problem 14: Performing slicing onto the Array from Problem 13
sec1 = comboArray[1]
sec2 = comboArray[2:]
sec3 = comboArray[3:14]
sec4 = comboArray[-6:]
sec5 = comboArray[-19:-8]
sec6 = comboArray[9:]
sec7 = comboArray[-1::-5]

print(sec1)
print(sec2)
print(sec3)
print(sec4)
print(sec5)
print(sec6)
print(sec7)



11
[12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[13 14 15 16 17 20 21 22 23 24 25]
[2 3 4 5 6 7]
[15 16 17 20 21 22 23 24 25 26 27]
[21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[ 7  2 25 20 13]


In [152]:
#Problem 15: Create a Dataframe from series
import pandas as pd
ingredients_list = ["Flour", "Milk", "Eggs", "Spam"]
quantity_list = ["4", "1","2","1"]
units_list = ["cups", "cups", "large", "can"]

ingredients = pd.Series(ingredients_list)
quantity = pd.Series(quantity_list)
units = pd.Series(units_list)

dinner = pd.concat((ingredients, quantity, units), axis= 1)
print(dinner)


       0  1      2
0  Flour  4   cups
1   Milk  1   cups
2   Eggs  2  large
3   Spam  1    can


In [154]:
#Problem 16: Use the data below to create a Dataframe

dict_studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }

studentData = pd.DataFrame(dict_studentData)
print(studentData)        

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [155]:
#Problem 17: Add a new column to the data frame in Problem 16
studentData['Deserts'] = ["ice cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       Waffles  
3  Carrot Halwa  


In [157]:
#Problem 18: Sort the Dataframe
studentData.sort_values(by = ['Name','address'], inplace = True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       Waffles  
0     ice cream  
1  Cashew Fudge  


In [164]:
#Problem 19: Save the below Dataframe as a CSV file
cows_and_goats = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
print(cows_and_goats)
cows_and_goats.to_csv('../Activities/cows_and_goats.csv')

        Cows  Goats
Year 1    12     22
Year 2    20     19


In [168]:
#Problem 20: Create and save a CSV file, then while making a copy, make change the CSV file and save it again
vegetables = pd.DataFrame({"Carrots": [3, 7],"Corn": [12, 5]}, index=['Spring', 'Summer'])
print(vegetables)
vegetables.to_csv('../Activities/vegetables.csv')
vegetables["Pumpkins"] = [1,2]
print(vegetables)
vegetables.to_csv('../Activities/vegetables_with_pumpkins.csv')

        Carrots  Corn
Spring        3    12
Summer        7     5
        Carrots  Corn  Pumpkins
Spring        3    12         1
Summer        7     5         2
